DB_USER="${POSTGRES_USER:=mehrdad}"

DB_PASSWORD="${POSTGRES_PASSWORD:=password}"

DB_NAME="${POSTGRES_DB:=profiles}"

DB_PORT="${POSTGRES_PORT:=5433}"


export PGPASSWORD="${DB_PASSWORD}"
export PGUSER="${DB_USER}"
export PGPORT="${DB_PORT}"
export PGNAME="${DB_NAME}"
